### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by autosquash** [lukasbach/chakra-ui-contextmenu#4]
Hi,
I would like to use this component in my projects, and I need to make some modifications on it, but I couldn't find a license file in the repo. Could you please add one? Thanks in advance.

Note: it seems that, legally, a repository is not considered open source without a license.

>  If a repository has no license, then all rights are reserved and it is not Open Source or Free. [Therefore, other users] cannot modify or redistribute this code without explicit permission from the copyright holder.

https://opensource.stackexchange.com/a/1721

**Comment by lukasbach** [comment]
Hi, good catch, seems like I forgot to add one. I added a MIT license file in the repo root, this should be sufficient to use it however you like.
